
[font]
size = 20.0

[keyboard]
bindings = [
    { key = "K", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "J", mods = "Control|Shift", action = "DecreaseFontSize" },
]

[general]
import = [
    "~/.config/alacritty/themes/rose-pine-moon.toml"
]

