import = ["$XDG_DATA_HOME/sesh/private.toml"]

[[session]]
name = "ssh"
path = "~/.ssh"
startup_command = "nvim config"

[[session]]
name = "dotfiles"
path = "~/Projects/personal/dotfiles/"
startup_command = "nvim ."

[[session]]
name = "default"
path = "~"
