local ls = require("luasnip")
local rep = require("luasnip.extras").rep
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("go", {
  s("import", {
    t("import ("),
    t({ "", '\t"' }),
    i(1, "package"),
    t('"'),
    t({ "", ")" }),
  }),
  s("const", {
    t("const "),
    i(1, "name"),
    t(" = "),
    i(2, "value"),
  }),
  s("consts", {
    t("const ("),
    t({ "", "\t" }),
    i(1, "name"),
    t(" = "),
    i(2, "value"),
    t({ "", ")" }),
  }),
  s("var", {
    t("var "),
    i(1, "name"),
    t(" "),
    i(2, "type"),
  }),
  s("vars", {
    t("var ("),
    t({ "", "\t" }),
    i(1, "name"),
    t(" "),
    i(2, "type"),
    t(" = "),
    i(3, "value"),
    t({ "", ")" }),
  }),
  s("typefunc", {
    t("type "),
    i(1, "name"),
    t(" func("),
    i(2),
    t(")"),
    i(0),
  }),
  s("typestruct", {
    t("type "),
    i(1, "name"),
    t(" struct "),
    t("{"),
    t({ "", "\t" }),
    i(0),
    t({ "", "}" }),
  }),
  s("typeinter", {
    t("type "),
    i(1, "name"),
    t(" interface "),
    t("{"),
    t({ "", "\t" }),
    i(0),
    t({ "", "}" }),
  }),
  s("func", {
    t("func "),
    i(1),
    t("("),
    i(2),
    t(")"),
    i(3),
    t(" {"),
    t({ "", "\t" }),
    i(0),
    t({ "", "}" }),
  }),
  s("funcmain", {
    t("func main () {"),
    t({ "", "\t" }),
    i(0),
    t({ "", "}" }),
  }),
  s("method", {
    t("func ("),
    i(1, "receiver"),
    t(" "),
    i(2, "type"),
    t(") "),
    i(3, "method"),
    t("("),
    i(4),
    t(")"),
    i(5),
    t(" {"),
    t({ "", "\t" }),
    i(0),
    t({ "", "}" }),
  }),
  s("switch", {
    t("switch "),
    i(1, "expression"),
    t(" {"),
    t({ "", "\t" }),
    t("case "),
    i(2, "condition"),
    t(":"),
    t({ "", "\t\t" }),
    i(3),
    t({ "", "\t" }),
    t("default:"),
    t({ "", "\t\t" }),
    i(4),
    t({"", "}"}),
    i(0),
  }),
  s("select", {
    t("select {"),
    t({ "", "\t" }),
    t("case "),
    i(1, "condition"),
    t(":"),
    t({ "", "\t\t" }),
    i(2),
    t({ "", "" }),
    t("}"),
    i(0),
  }),

  s("case", {
    t("case "),
    i(1, "condition"),
    t(":"),
    t({ "", "\t" }),
    i(2),
    t({ "", "" }),
    i(0),
  }),

  s("for", {
    t("for "),
    i(1),
    t(" {"),
    t({ "", "\t" }),
    i(0),
    t({ "", "" }),
    t("}"),
  }),

  s("fori", {
    t("for "),
    i(1, "i"),
    t(" := "),
    i(2, "0"),
    t("; "),
    rep(1),
    t(" < "),
    i(3, "count"),
    t("; "),
    rep(1),
    t("++ {"),
    t({ "", "\t" }),
    i(0),
    t({ "", "" }),
    t("}"),
  }),

  s("forr", {
    t("for "),
    i(1, "_"),
    t(", "),
    i(2, "v"),
    t(" :="),
    t(" range "),
    i(3, "iterable"),
    t(" {"),
    t({ "", "\t" }),
    i(0),
    t({ "", "" }),
    t("}"),
  }),

  s("chan", {
    t("chan "),
    i(1, "type"),
  }),

  s("map", {
    t("map ["),
    i(1, "type"),
    t("]"),
    i(2, "type"),
  }),

  s("if", {
    t("if "),
    i(1, "condition"),
    t(" {"),
    t({ "", "\t" }),
    i(2),
    t({ "", "" }),
    t("}"),
    i(0),
  }),

  s("else", {
    t("else {"),
    t({ "", "\t" }),
    i(0),
    t({ "", "" }),
    t("}"),
  }),

  s("elseif", {
    t("else if "),
    i(1, "condition"),
    t(" {"),
    t({ "", "\t" }),
    i(2),
    t({ "", "}" }),
    i(0),
  }),

  s("ifelse", {
    t("if "),
    i(1, "condition"),
    t(" {"),
    t({ "", "\t" }),
    i(2),
    t({ "", "" }),
    t("}"),
    i(3),
    t(" else {"),
    t({ "", "\t" }),
    i(0),
    t({ "", "" }),
    t("}"),
  }),

  s("iferror", {
    t("if err != nil {"),
    t({ "", "\t" }),
    t("return "),
    i(1, "err"),
    i(0),
    t({ "", "}" }),
  }),

  s("Pmain", {
    t("package main"),
    t({ "", "" }),
    t({ "", "" }),
    t("func main() {"),
    t({ "", "\t" }),
    i(0),
    t({ "", "}" }),
  }),

  s("printf", {
    t('fmt.Printf("'),
    i(1),
    t('")'),
  }),

  s("Go", {
    t('wg.Go(func(){'),
    t({"", "\t\t"}),
    i(1),
    t({"", ""}),
    t('})'),
  }),

})
