; vim: ft=ini

; source: https://github.com/mangowm/mango/wiki/xdg-portals#portal-configuration
[preferred]
default=gtk
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
; org.freedesktop.impl.portal.Secret=gnome-keyring
; org.freedesktop.impl.portal.Inhibit=none
