#!/usr/bin/env sh

# this is a simple config for herbstluftwm
# Draw some inspiration from this guy on youtube  https://github.com/jdpedersen1/Void-Herbstluftwm
# https://www.youtube.com/watch?v=mtwnA1U1Urk&t=241s
# check here for scratchpad https://github.com/herbstluftwm/herbstluftwm/blob/master/scripts/q3terminal.sh

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# hc keybind $Mod-q quit
hc keybind $Mod-q close
hc keybind $Mod-Shift-r reload

## Spawn processes
# hc keybind $Mod-Shift-Return spawn "${TERMINAL:-st}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Shift-Return spawn "${TERMINAL:-st}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-d spawn quickshell ipc call AppLauncher toggle
hc keybind $Mod-c spawn quickshell ipc call NotificationServer toggleCenter
hc keybind $Mod-m spawn quickshell ipc call MusicPlayer toggle
hc keybind $Mod-o spawn ~/.local/bin/scratchpad

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-v       split   right   0.5
hc keybind $Mod-s       split   bottom  0.5

# let the current frame explode into subframes
# hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        # hc keybind "$Mod-$key" \
            # or , and . compare tags.focus.index = "$i" \
            #          . use_previous \
               # , use_index "$i"
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
# hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-Space floating toggle
# hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Tab                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-n           cycle_all +1
hc keybind $Mod-p           cycle_all -1
# hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# multimedia

hc keybind XF86AudioRaiseVolume spawn wpctl set-volume @DEFAULT_SINK@ 5%+
hc keybind XF86AudioLowerVolume spawn wpctl set-volume @DEFAULT_SINK@ 5%-
hc keybind XF86MonBrightnessUp spawn brightnessctl set +10%
hc keybind XF86MonBrightnessDown spawn brightnessctl set 10%-

#
# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
# hc set frame_border_active_color '#222222cc'
# hc set frame_border_normal_color '#101010cc'
# hc set frame_bg_normal_color '#565656aa'
# hc set frame_bg_active_color '#345F0Caa'
# hc set frame_border_width 5
# hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.title_height 0
hc attr theme.title_when never
hc attr theme.title_font 'Dejavu Sans:pixelsize=12'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
# hc attr theme.title_depth 3  # space below the title's baseline
# hc attr theme.active.color '#345F0Cef'
# hc attr theme.title_color '#ffffff'
# hc attr theme.normal.color '#323232dd'
# hc attr theme.urgent.color '#7811A1dd'
# hc attr theme.tab_color '#1F1F1Fdd'
# hc attr theme.active.tab_color '#2B4F0Add'
# hc attr theme.active.tab_outer_color '#6C8257dd'
# hc attr theme.active.tab_title_color '#ababab'
# hc attr theme.normal.title_color '#898989'
# hc attr theme.inner_width 1
# hc attr theme.inner_color black
# hc attr theme.border_width 0
# hc attr theme.floating.border_width 4
# hc attr theme.floating.outer_width 1
# hc attr theme.floating.outer_color black
# hc attr theme.active.inner_color '#789161'
# hc attr theme.urgent.inner_color '#9A65B0'
# hc attr theme.normal.inner_color '#606060'

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 1
hc set frame_padding 5
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule class=qutebrowser tag=2
hc rule title~"scratchpad" floating=on floatplacement=center floating_geometry=1600x750
hc rule title~"AppLauncher" floating=on floatplacement=center floating_geometry=1600x750
hc rule title~"NotificationCenter" floating=on floatplacement=center floating_geometry=1600x750
hc rule title~"MusicPlayer" floating=on floatplacement=center floating_geometry=700x300
hc rule class=zen tag=2
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done

quickshell -c ~/.config/quickshell/
